name: Weekly Extract

on:
  push:
    branches: ["main"]
    paths: ["tn_gazette_archiver.py", "scrape_gazettes.py", "archive_new_links.py"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight UTC

permissions:
  contents: write

jobs:
  run:
    name: Scrape & Archive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Scrape new Extraordinary Gazettes
        run: python scrape_gazettes.py

      - name: Archive unarchived PDF links to Wayback Machine
        run: python archive_new_links.py --delay 2

      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "Weekly scrape and Wayback archival"
