name: Weekly Extract

on:
  push:
    branches: ["main"]
    paths: ["tn_gazette_archiver.py"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    name: Run tn_gazette_archiver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET }}
      - uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Archiver
        run: python tn_gazette_archiver.py
      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
